# Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split

# Loading dataset

In [2]:
data= load_iris()
X = data.data
y =  data.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9,random_state=1)

# KNN Algorithm

In [4]:
final_labels = []
for i in range(len(X_test)):
    distances = np.zeros(len(X_train))
    for j in range(len(X_train)):
        distances[j] = np.linalg.norm(X_test[i]-X_train[j])
    min_d_indices = np.argsort(distances,axis=0)[:5]
    labels = y_train[min_d_indices]
    if i in [0,1,2,3]:
        print(labels)
    d = dict()
    for k in labels:
        if k not in d.keys():
            d[k] = 1
        else:
            d[k] += 1
    for k in d.keys():
        if d[k] == max(d.values()):
            final_labels.append(k)
            break
print('Confusion Matrix:')
print(confusion_matrix(y_test,final_labels))
print('Accuracy Score:', accuracy_score(y_test,final_labels))


[0 0 0 1 1]
[1 1 1 0 0]
[1 1 1 2 1]
[0 0 0 1 1]
Confusion Matrix:
[[47  0  0]
 [ 0 39  5]
 [ 0  2 42]]
Accuracy Score: 0.9481481481481482
